new_tab node_process
layout splits

launch --var first-window= --cwd="~/github/ocean-network-express/backend/" pnpm start:dev
launch --location=vsplit  --cwd="~/github/ocean-network-express/bff/" pnpm start:dev
launch --location=hsplit  bind-ods
resize_window shorter 5
launch --type=background --allow-remote-control sh -c 'kitten @ focus-window --match var:first-window; kitten @ launch --location=hsplit --cwd="~/github/ocean-network-express/web/" pnpm dev'

new_tab development
layout splits
launch --cwd="~/github/ocean-network-express/"
launch --type=background --allow-remote-control sh -c 'kitten @ focus-tab --match index:1'
