-- Snapshot translated from monitors.conf (auto-generated by Quickshell MonitorManager)
-- at migration time. See the caveat in hyprland.lua: Quickshell still writes this as
-- monitors.conf in hyprlang syntax on every edit, so this file needs the Quickshell
-- script updated to keep it current, or manual re-sync after monitor changes.
hl.monitor({ output = "eDP-1",    mode = "1920x1200@60.00", position = "-1x-1",   scale = 1 })
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@60.00", position = "1919x63", scale = 1 })
