#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr


# set some bsp specific
bspc monitor DisplayPort-1 -d 1 2 3 4 5
bspc monitor HDMI-A-0 -d 6 7 8 9
bspc monitor DisplayPort-2 -d 0

bspc config window_gap 12
bspc config border_width 1

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
